### ISSUE TITLE
Error opening schematic in latest Eagle 9.4.1

### ISSUE THREAD

**Issue by dattasaurabh82** [magkopian/raspberry-pi-compute-module-base-board#1]
Hello I have trouble opening the .sch file in Latest Autodesk eagle. 
Here's what it shows: [error window dialog](https://i.ibb.co/5B8Dkq0/Screen-Shot-2019-06-12-at-12-17-03-PM.png)
Any leads would help.

**Comment by magkopian** [comment]
The board is designed on [KiCAD](http://kicad-pcb.org/) not Eagle, you need to use KiCAD to open the schematic and the rest of the design files.
